### ISSUE TITLE
Get INVALID REQUEST from chesspastebin.com using PyChess Share game menu

### ISSUE THREAD

**Issue by gbtami** [toomasr/jspgnviewer#1]
Hey Toomas!
Can you take a look at https://github.com/pychess/pychess/blob/master/lib/pychess/Savers/chesspastebin.py please? Had PyChess apikey expired or something? It worked before.

**Comment by toomasr** [comment]
I'm sorry, my bad. I had all traffic rerouted to https. I added an exception to the API.

Any chance you can upgrade the call to https? I will keep supporting http but as plain text is kind of dying then I think being ready for the future would be good.

**Comment by gbtami** [comment]
If I change to https I get empty response.
```
URL: https://www.chesspastebin.com/api/add/
data: b'apikey=a137d919b75c8766b082367610189358cfb1ba70&pgn=%5BEvent+%22Helyi+esem%C3%A9ny%22%5D%0A%5BSite+%22Helyben%22%5D%0A%5BDate+%222019.04.16%22%5D%0A%5BRound+%221%22%5D%0A%5BWhite+%22tamas%22%5D%0A%5BBlack+%22Vendeg%22%5D%0A%5BResult+%220-1%22%5D%0A%5BWhiteClock+%220%3A05%3A00.000%22%5D%0A%5BBlackClock+%220%3A05%3A00.000%22%5D%0A%5BTimeControl+%22300%2B0%22%5D%0A%0A+0-1%0A%0A&name=PyChess&sandbox=true'
response.read() gives ID: b''
Traceback (most recent call last):
  File "/home/tamas/pychess/lib/pychess/Main.py", line 278, in on_share_game_activate
    chesspastebin.paste(gmwidg.gamemodel)
  File "/home/tamas/pychess/lib/pychess/Savers/chesspastebin.py", line 54, in paste
    link = "https://www.chesspastebin.com/?p=%s" % int(ID)
ValueError: invalid literal for int() with base 10: b''
```

**Comment by toomasr** [comment]
Not sure what had changed but one of my regexed started failing. Maybe a Wordpress upgrade changed output buffering caches. Anyways, it is fixed now. Sorry for the trouble.

To debug this I extracted the chesspastebin code in pychess and wrote a test for it. As I'm on a Mac then I don't have any of the GTK stuff so I butchered things a little bit. It is not that easy for me to figure out what is the best way to do this as I know how to write python but not how to setup a project in a clean manner.

This is what I wrote. Maybe you can refactor this into a test for easier debugging in the future?

I used `PYTHONPATH=../lib python3 chesspastebin.py` to run this.

https://gist.github.com/toomasr/476b9ffa2e520c389629adffacd881a1

**Comment by gbtami** [comment]
@toomasr it's working now as expected, thx a lot. Very much appreciated!
